name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "I appreciate you pointing me to the problem, and as soon as time allows, I will look into it. Thank you!"
        pr-message: "I appreciate you creating your first pull request and look forward to reviewing your future contributions."
